all:
    children:
        site:
            hosts:
                server:
                    ansible_connection: ssh
                    ansible_user: root
                    ansible_host: 95.163.230.75
                    ansible_port: 22